// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzR2Gc8cwja-wQ9F2zB21xy5lTAXuhJh0',
    appId: '1:836261625775:web:11a92941b84ee676a7b95a',
    messagingSenderId: '836261625775',
    projectId: 'scoutvista-efe76',
    authDomain: 'scoutvista-efe76.firebaseapp.com',
    storageBucket: 'scoutvista-efe76.firebasestorage.app',
    measurementId: 'G-FM2M5BXZ2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7XOTmMpeJ29ao8JfxTrnkSu9f_d6wfqE',
    appId: '1:836261625775:android:17522357b53ec0d0a7b95a',
    messagingSenderId: '836261625775',
    projectId: 'scoutvista-efe76',
    storageBucket: 'scoutvista-efe76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9gNfODnMtJinLWFvDPOHAgL5EpmTOG3c',
    appId: '1:836261625775:ios:214e58f2e24bc1efa7b95a',
    messagingSenderId: '836261625775',
    projectId: 'scoutvista-efe76',
    storageBucket: 'scoutvista-efe76.firebasestorage.app',
    iosBundleId: 'com.example.coachAiV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9gNfODnMtJinLWFvDPOHAgL5EpmTOG3c',
    appId: '1:836261625775:ios:214e58f2e24bc1efa7b95a',
    messagingSenderId: '836261625775',
    projectId: 'scoutvista-efe76',
    storageBucket: 'scoutvista-efe76.firebasestorage.app',
    iosBundleId: 'com.example.coachAiV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzR2Gc8cwja-wQ9F2zB21xy5lTAXuhJh0',
    appId: '1:836261625775:web:4eee5430da645691a7b95a',
    messagingSenderId: '836261625775',
    projectId: 'scoutvista-efe76',
    authDomain: 'scoutvista-efe76.firebaseapp.com',
    storageBucket: 'scoutvista-efe76.firebasestorage.app',
    measurementId: 'G-MKZ1SLN1YB',
  );

}